### ISSUE TITLE
The e-mail address contains illegal characters 

### ISSUE THREAD

**Issue by ccoulson** [ccoulson/import_test#213]
<b>srinivas8668[CodePlex]</b> <br />hello I am using this solution when I added this to my TFS. and trying to bulid I am getting some error like

D:\Visigo.Sharepoint.FormsBasedAuthentication\Visigo.Sharepoint.FormsBasedAuthentication\build\updateresources.batquotquot exited with code 1. Visigo.Sharepoint.FormsBasedAuthentication

for this I have Removed the below value 

this valuequot$(ProjectDir)build\updateresources.batquot from build event in VS2010[Pre-build event command line I have removed completely from my solution

Than i am able to build and deploy . after adding membershiprequest web part and fill details and clicking on CreateUser Button I am getting this error

An unexpected error has occurred. Please contact your administrator if this problem persists, or check the SharePoint log file for more details

from Sharepoint logs folder I am getting this below information
160008: The e-mail address 'xxx_cmr86@gmail.com' contains illegal characters.
Cannot complete this action. Please try again.ltnativehrgt0x80004005lt/nativehrgtltnativestackgtlt/nativestackgt 8fe8b0fe-6855-4ef1-81fd-3640f4f9509d

08/09/2013 15:02:50.80 w3wp.exe (0x18A0) 0x22A4 SharePoint 2010 FBA Pack General 0000 High SendEmail failed 8fe8b0fe-6855-4ef1-81fd-3640f4f9509d

08/09/2013 15:02:50.83 w3wp.exe (0x18A0) 0x22A4 SharePoint 2010 FBA Pack General 0000 High System.Exception: Error sending mail notification at Visigo.Sharepoint.FormsBasedAuthentication.MembershipRequest.ApproveMembership(MembershipRequest request, SPWeb web)
 8fe8b0fe-6855-4ef1-81fd-3640f4f9509d 

how can fix it I have taken the latest solution only my out going email setting also done

**Comment by ccoulson** [comment]
<b>ccoulson[CodePlex]</b> <br />Usually if it's an smtp error the smtp error message will show in the logs. In this case it doesn't look like it even got that far. Do you have your outgoing mail setup in SharePoint? Do other emails from sharepoint work?

**Comment by ccoulson** [comment]
<b>martind[CodePlex]</b> <br />Here is the error from the SharePoint log. Yes, running telnet from the SharePoint and sending to the same email address that fails in the web part.


11/26/2013 09:26:38.48 w3wp.exe (0x1488) 0x20E4 SharePoint 2010 FBA Pack General 0000 High SendEmail failed 0152a9ce-980c-4e58-96e3-e548160e52a1
11/26/2013 09:26:38.49 w3wp.exe (0x1488) 0x20E4 SharePoint 2010 FBA Pack General 0000 High System.Exception: Error sending mail notification at Visigo.Sharepoint.FormsBasedAuthentication.MembershipRequest.ApproveMembership(MembershipRequest request, SPWeb web)
 0152a9ce-980c-4e58-96e3-e548160e52a1
11/26/2013 09:26:38.49 w3wp.exe (0x1488) 0x20E4 SharePoint 2010 FBA Pack General 0000 High System.Exception: Error sending mail notification at Visigo.Sharepoint.FormsBasedAuthentication.MembershipRequest.ApproveMembership(MembershipRequest request, SPWeb web)
 at Visigo.Sharepoint.FormsBasedAuthentication.MembershipRequestControl.OnCreatedUserb__0() 0152a9ce-980c-4e58-96e3-e548160e52a1

**Comment by ccoulson** [comment]
<b>ccoulson[CodePlex]</b> <br />Can you please paste the error from the sharepoint log.

Also, are you running telnet from the sharepoint machine, and sending an email to the same email address that fails in the web part?

**Comment by ccoulson** [comment]
<b>martind[CodePlex]</b> <br />my telnet is working on my Windows 2008 R2 server but I'm getting this error when I try to create a user using the 'Membership Request' web part.

'An unexpected error has occurred. Please contact your administrator if this problem persists, or check the SharePoint log file for more details.'

I checked the log file and was told that I'm getting a send mail error but I'm able to send mail with telnet. Please help if you can.

**Comment by ccoulson** [comment]
<b>ccoulson[CodePlex]</b> <br />I just tried the email address on my side and it worked fine. I believe the error is coming from your smtp server. You can try using telnet to send an email through the smtp server to see if you get the same error:

http://technet.microsoft.com/en-us/library/aa995718(v=exchg.65).aspx

Do other email addresses work?
